In [11]:
import dash
import dash_core_components as dcc
from dash import dcc,html
import plotly.express as px
import pandas as pd
# import pymssql

df = pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [12]:
app = dash.Dash(__name__)

In [13]:
df1 = df[['MaxHR','RestingBP']]
fig1 = px.scatter(df1, x='MaxHR',y='RestingBP',title='MaxHR vs RestingBP')

In [14]:
df2 = df[['RestingBP','Cholesterol']]
fig2 = px.scatter(df2, x='RestingBP',y='Cholesterol',title='RestingBP vs Cholesterol')

In [26]:
df3 = df['ChestPainType'].value_counts().keys().tolist()
df4 = df['ChestPainType'].value_counts().tolist()
fig3 = px.bar(y=df3,x=df4,orientation='h',title='Reported Chest Pain Type')

In [27]:
app.layout = html.Div(children=[
    html.H1(children='Heart disease indicators'),

    html.Div(children='''
        RestingBP, MaxHR, and Cholesterol
    '''),

    dcc.Graph(
        id='MaxHR-vs-RestingBP',
        figure=fig1
    ),

    dcc.Graph(
        id='RestingBP-vs-Cholesterol',
        figure=fig2
    ),

    dcc.Graph(
        id='ChestPainType',
        figure=fig3
    )
])

if __name__ == '__main__':
    app.run_server(debug=True,use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on